FROM golang:1.17-alpine3.15 AS builder
WORKDIR /app
COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.io,direct
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -o main .

FROM alpine:3.15 AS production
COPY --from=builder /app/main .
CMD ["./main"]
